set(CMAKE_SYSTEM_NAME Linux)
# set(CMAKE_SYSTEM_VERSION 6.1)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
#set(CMAKE_RC_COMPILER rc)
#set(CMAKE_LINKER lld-link)


set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)