set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 6.1)

set(CMAKE_GENERATOR "Visual Studio 17 2022")

add_compile_definitions(_WIN32_WINNT=0x0601) # Windows 7
add_compile_definitions(WIN32_LEAN_AND_MEAN)
set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)