name: CMake build Windows All

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  win:

    runs-on: windows
    strategy:
      matrix:
        config:
          - name: win2k-x86-Debug
            arch: x86
            type: Debug
            toolchain: "cmake/toolchains/win2k.cmake"
            generator: "MinGW Makefiles"

          - name: win2k-x86-Release
            arch: x86
            type: Release
            toolchain: "cmake/toolchains/win2k.cmake"
            generator: "MinGW Makefiles"

          - name: winxp-x86-Debug
            arch: x86
            type: Debug
            toolchain: "cmake/toolchains/winxp.cmake"
            generator: "MinGW Makefiles"

          - name: winxp-x86-Release
            arch: x86
            type: Release
            toolchain: "cmake/toolchains/winxp.cmake"
            generator: "MinGW Makefiles"

          - name: winx86-Debug
            arch: x86
            type: Debug
            tests: true
            toolchain: "cmake/toolchains/win.cmake"
            generator: "Visual Studio 17 2022"

          - name: winx86-Release
            arch: x86
            type: Release
            tests: true
            toolchain: "cmake/toolchains/win.cmake"
            generator: "Visual Studio 17 2022"

          - name: winx64-Debug
            arch: x64
            type: Debug
            tests: true
            toolchain: "cmake/toolchains/win.cmake"
            generator: "Visual Studio 17 2022"

          - name: winx64-Release
            arch: x64
            type: Release
            tests: true
            toolchain: "cmake/toolchains/win.cmake"
            generator: "Visual Studio 17 2022"


    steps:
    - uses: actions/checkout@v4

    - name: pull googleTest
      if: matrix.config.tests
      run: git clone https://github.com/google/googletest.git ${{github.workspace}}/dlljbltest/googletest

    - name: Configure CMake
      run: cmake -S . -B build-${{matrix.config.name}} -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/${{matrix.config.toolchain}}" -DCMAKE_BUILD_TYPE=${{matrix.config.type}} -G "${{matrix.config.generator}}"

    - name: Build Project
      run: cmake --build build-${{matrix.config.name}} --config ${{matrix.config.type}}

    - name: Upload Test Project
      if: matrix.config.tests
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dlljbltest_${{matrix.config.name}}
        path: |
          build-${{matrix.config.name}}/dlljbltest/${{matrix.config.type}}/*
          build-${{matrix.config.name}}/dlljbltest/${{matrix.config.type}}/*
        if-no-files-found: error

    - name: Upload library Files ${{matrix.config.name}}
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dlljbl_${{matrix.config.name}}
        path: |
          build-${{matrix.config.name}}/dlljbl/*.a
          build-${{matrix.config.name}}/dlljbl/*.lib
          build-${{matrix.config.name}}/dlljbl/*.pdb
          build-${{matrix.config.name}}/dlljbl/*.exe
          build-${{matrix.config.name}}/dlljbl/${{matrix.config.type}}/*.exe
          build-${{matrix.config.name}}/dlljbl/${{matrix.config.type}}/*.lib
          build-${{matrix.config.name}}/dlljbl/${{matrix.config.type}}/*.pdb
        if-no-files-found: error

    - name: cleanup
      run: Get-ChildItem -Recurse;
        Remove-Item -Recurse -Force *;
      working-directory: ${{github.workspace}}
      continue-on-error: true
