name: CMake build Windows CMake MinGW

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  win:

    runs-on: windows
    strategy:
      matrix:
        config:
          - name: win2k-x86-Debug
            arch: x86
            type: Debug
            toolchain: "cmake/toolchains/win2k.cmake"
            generator: "MinGW Makefiles"

          - name: win2k-x86-Release
            arch: x86
            type: Release
            toolchain: "cmake/toolchains/win2k.cmake"
            generator: "MinGW Makefiles"

          - name: winxp-x86-Debug
            arch: x86
            type: Debug
            toolchain: "cmake/toolchains/winxp.cmake"
            generator: "MinGW Makefiles"

          - name: winxp-x86-Release
            arch: x86
            type: Release
            toolchain: "cmake/toolchains/winxp.cmake"
            generator: "MinGW Makefiles"

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build-${{matrix.config.name}} -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/${{matrix.config.toolchain}}" -DCMAKE_BUILD_TYPE=${{matrix.config.type}} -G "${{matrix.config.generator}}"

    - name: Build Project
      run: cmake --build build-${{matrix.config.name}} --config ${{matrix.config.type}}

    - name: Upload legacy test project
      uses: actions/upload-artifact@v4.6.2
      with:
        name: legacyTest_${{matrix.config.name}}
        path: |
          build-${{matrix.config.name}}/legacyTest/*.a
          build-${{matrix.config.name}}/legacyTest/*.lib
          build-${{matrix.config.name}}/legacyTest/*.dll
          build-${{matrix.config.name}}/legacyTest/*.exe
        if-no-files-found: error


    - name: Upload library Files ${{matrix.config.name}}
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dlljbl_${{matrix.config.name}}
        path: |
          build-${{matrix.config.name}}/dlljbl/*.a
          build-${{matrix.config.name}}/dlljbl/*.lib
          build-${{matrix.config.name}}/dlljbl/*.dll
          build-${{matrix.config.name}}/dlljbl/*.exe
        if-no-files-found: error

    - name: cleanup
      run: Get-ChildItem -Recurse;
        Remove-Item -Recurse -Force *;
      working-directory: ${{github.workspace}}
      continue-on-error: true
